# coding: utf-8

"""
    OGC API - Processes

    Example API Definition for OGC API - Processes

    The version of the OpenAPI document: 0.1
    Contact: info@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, Field, StrictInt
from typing_extensions import Annotated

from unity_sps_ogc_processes_api.models.extent_spatial_grid_inner_coordinates_inner import (
    ExtentSpatialGridInnerCoordinatesInner,
)
from unity_sps_ogc_processes_api.models.extent_spatial_grid_inner_resolution import (
    ExtentSpatialGridInnerResolution,
)

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ExtentSpatialGridInner(BaseModel):
    """
    ExtentSpatialGridInner
    """  # noqa: E501

    coordinates: Optional[Annotated[List[ExtentSpatialGridInnerCoordinatesInner], Field(min_length=1)]] = (
        Field(
            default=None,
            description="List of coordinates along the dimension for which data organized as an irregular grid in the collection is available (e.g., 2, 10, 80, 100).",
        )
    )
    cells_count: Optional[StrictInt] = Field(
        default=None,
        description="Number of samples available along the dimension for data organized as a regular grid. For values representing the whole area of contiguous cells spanning _resolution_ units along the dimension, this will be (_upperBound_ - _lowerBound_) / _resolution_. For values representing infinitely small point cells spaced by _resolution_ units along the dimension, this will be (_upperBound_ - _lowerBound_) / _resolution_ + 1.",
        alias="cellsCount",
    )
    resolution: Optional[ExtentSpatialGridInnerResolution] = None
    __properties: ClassVar[List[str]] = ["coordinates", "cellsCount", "resolution"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExtentSpatialGridInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in coordinates (list)
        _items = []
        if self.coordinates:
            for _item in self.coordinates:
                if _item:
                    _items.append(_item.to_dict())
            _dict["coordinates"] = _items
        # override the default output from pydantic by calling `to_dict()` of resolution
        if self.resolution:
            _dict["resolution"] = self.resolution.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ExtentSpatialGridInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "coordinates": (
                    [
                        ExtentSpatialGridInnerCoordinatesInner.from_dict(_item)
                        for _item in obj.get("coordinates")
                    ]
                    if obj.get("coordinates") is not None
                    else None
                ),
                "cellsCount": obj.get("cellsCount"),
                "resolution": (
                    ExtentSpatialGridInnerResolution.from_dict(obj.get("resolution"))
                    if obj.get("resolution") is not None
                    else None
                ),
            }
        )
        return _obj
