# coding: utf-8

"""
    OGC API - Processes

    Example API Definition for OGC API - Processes

    The version of the OpenAPI document: 0.1
    Contact: info@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Dict, List, Optional, Union

from pydantic import BaseModel, ValidationError, field_validator
from typing_extensions import Literal

from unity_sps_ogc_processes_api.models.geo_json_line_string import GeoJSONLineString
from unity_sps_ogc_processes_api.models.geo_json_multi_line_string import (
    GeoJSONMultiLineString,
)
from unity_sps_ogc_processes_api.models.geo_json_multi_point import GeoJSONMultiPoint
from unity_sps_ogc_processes_api.models.geo_json_multi_polygon import (
    GeoJSONMultiPolygon,
)
from unity_sps_ogc_processes_api.models.geo_json_point import GeoJSONPoint
from unity_sps_ogc_processes_api.models.geo_json_polygon import GeoJSONPolygon

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

GEOJSONFEATUREGEOMETRY_ONE_OF_SCHEMAS = [
    "GeoJSONLineString",
    "GeoJSONMultiLineString",
    "GeoJSONMultiPoint",
    "GeoJSONMultiPolygon",
    "GeoJSONPoint",
    "GeoJSONPolygon",
]


class GeoJSONFeatureGeometry(BaseModel):
    """
    GeoJSONFeatureGeometry
    """

    # data type: GeoJSONPoint
    oneof_schema_1_validator: Optional[GeoJSONPoint] = None
    # data type: GeoJSONLineString
    oneof_schema_2_validator: Optional[GeoJSONLineString] = None
    # data type: GeoJSONPolygon
    oneof_schema_3_validator: Optional[GeoJSONPolygon] = None
    # data type: GeoJSONMultiPoint
    oneof_schema_4_validator: Optional[GeoJSONMultiPoint] = None
    # data type: GeoJSONMultiLineString
    oneof_schema_5_validator: Optional[GeoJSONMultiLineString] = None
    # data type: GeoJSONMultiPolygon
    oneof_schema_6_validator: Optional[GeoJSONMultiPolygon] = None
    actual_instance: Optional[
        Union[
            GeoJSONLineString,
            GeoJSONMultiLineString,
            GeoJSONMultiPoint,
            GeoJSONMultiPolygon,
            GeoJSONPoint,
            GeoJSONPolygon,
        ]
    ] = None
    one_of_schemas: List[str] = Literal[
        "GeoJSONLineString",
        "GeoJSONMultiLineString",
        "GeoJSONMultiPoint",
        "GeoJSONMultiPolygon",
        "GeoJSONPoint",
        "GeoJSONPolygon",
    ]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        GeoJSONFeatureGeometry.model_construct()
        error_messages = []
        match = 0
        # validate data type: GeoJSONPoint
        if not isinstance(v, GeoJSONPoint):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `GeoJSONPoint`"
            )
        else:
            match += 1
        # validate data type: GeoJSONLineString
        if not isinstance(v, GeoJSONLineString):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `GeoJSONLineString`"
            )
        else:
            match += 1
        # validate data type: GeoJSONPolygon
        if not isinstance(v, GeoJSONPolygon):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `GeoJSONPolygon`"
            )
        else:
            match += 1
        # validate data type: GeoJSONMultiPoint
        if not isinstance(v, GeoJSONMultiPoint):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `GeoJSONMultiPoint`"
            )
        else:
            match += 1
        # validate data type: GeoJSONMultiLineString
        if not isinstance(v, GeoJSONMultiLineString):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `GeoJSONMultiLineString`"
            )
        else:
            match += 1
        # validate data type: GeoJSONMultiPolygon
        if not isinstance(v, GeoJSONMultiPolygon):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `GeoJSONMultiPolygon`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in GeoJSONFeatureGeometry with oneOf schemas: GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in GeoJSONFeatureGeometry with oneOf schemas: GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into GeoJSONPoint
        try:
            instance.actual_instance = GeoJSONPoint.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONLineString
        try:
            instance.actual_instance = GeoJSONLineString.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONPolygon
        try:
            instance.actual_instance = GeoJSONPolygon.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONMultiPoint
        try:
            instance.actual_instance = GeoJSONMultiPoint.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONMultiLineString
        try:
            instance.actual_instance = GeoJSONMultiLineString.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONMultiPolygon
        try:
            instance.actual_instance = GeoJSONMultiPolygon.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into GeoJSONFeatureGeometry with oneOf schemas: GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into GeoJSONFeatureGeometry with oneOf schemas: GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
