# coding: utf-8

"""
    OGC API - Processes

    Example API Definition for OGC API - Processes

    The version of the OpenAPI document: 0.1
    Contact: info@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import re  # noqa: F401
from enum import Enum

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class JobControlOptions(str, Enum):
    """
    JobControlOptions
    """

    """
    allowed enum values
    """
    SYNC_MINUS_EXECUTE = "sync-execute"
    ASYNC_MINUS_EXECUTE = "async-execute"
    DISMISS = "dismiss"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobControlOptions from a JSON string"""
        return cls(json.loads(json_str))
