# coding: utf-8

"""
    OGC API - Processes

    Example API Definition for OGC API - Processes

    The version of the OpenAPI document: 0.1
    Contact: info@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
from typing import Any, Dict, List, Union

from pydantic import RootModel, ValidationError, model_validator
from unity_sps_ogc_processes_api.models.execution_unit import ExecutionUnit
from unity_sps_ogc_processes_api.models.link import Link
from unity_sps_ogc_processes_api.models.qualified_input_value import QualifiedInputValue


class OgcapppkgExecutionUnit(RootModel):
    root: Union[
        ExecutionUnit,
        Link,
        QualifiedInputValue,
        List[Union[ExecutionUnit, Link, QualifiedInputValue]],
    ]

    @model_validator(mode="before")
    @classmethod
    def validate_type(cls, value):
        if isinstance(value, dict):
            for schema in [ExecutionUnit, Link, QualifiedInputValue]:
                try:
                    return schema(**value)
                except ValidationError:
                    pass
        elif isinstance(value, list):
            return [cls.validate_type(item) for item in value]
        elif isinstance(value, (ExecutionUnit, Link, QualifiedInputValue)):
            return value
        raise ValueError(f"Invalid type for OgcapppkgExecutionUnit: {type(value)}")

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> OgcapppkgExecutionUnit:
        return cls(root=cls.validate_type(obj))

    @classmethod
    def from_json(cls, json_str: str) -> OgcapppkgExecutionUnit:
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        if isinstance(self.root, list):
            return [item.model_dump() for item in self.root]
        return self.root.model_dump()

    def to_json(self) -> str:
        return json.dumps(self.to_dict())

    def __getattr__(self, name: str) -> Any:
        return getattr(self.root, name)

    def __repr__(self) -> str:
        return f"OgcapppkgExecutionUnit({self.root!r})"

    def to_str(self) -> str:
        return pprint.pformat(self.model_dump())
