# coding: utf-8

"""
    OGC API - Processes

    Example API Definition for OGC API - Processes

    The version of the OpenAPI document: 0.1
    Contact: info@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, Field, StrictStr, field_validator
from typing_extensions import Annotated

from unity_sps_ogc_processes_api.models.exception import Exception
from unity_sps_ogc_processes_api.models.link import Link
from unity_sps_ogc_processes_api.models.status_code import StatusCode

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class StatusInfo(BaseModel):
    """
    StatusInfo
    """  # noqa: E501

    process_id: Optional[StrictStr] = Field(default=None, alias="processID")
    type: StrictStr
    job_id: StrictStr = Field(alias="jobID")
    status: StatusCode
    message: Optional[StrictStr] = None
    exception: Optional[Exception] = None
    created: Optional[datetime] = None
    started: Optional[datetime] = None
    finished: Optional[datetime] = None
    updated: Optional[datetime] = None
    progress: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = None
    links: Optional[List[Link]] = None
    __properties: ClassVar[List[str]] = [
        "processID",
        "type",
        "jobID",
        "status",
        "message",
        "exception",
        "created",
        "started",
        "finished",
        "updated",
        "progress",
        "links",
    ]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ("process"):
            raise ValueError("must be one of enum values ('process')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StatusInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of exception
        if self.exception:
            _dict["exception"] = self.exception.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict())
            _dict["links"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of StatusInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "processID": obj.get("processID"),
                "type": obj.get("type"),
                "jobID": obj.get("jobID"),
                "status": obj.get("status"),
                "message": obj.get("message"),
                "exception": (
                    Exception.from_dict(obj.get("exception")) if obj.get("exception") is not None else None
                ),
                "created": obj.get("created"),
                "started": obj.get("started"),
                "finished": obj.get("finished"),
                "updated": obj.get("updated"),
                "progress": obj.get("progress"),
                "links": (
                    [Link.from_dict(_item) for _item in obj.get("links")]
                    if obj.get("links") is not None
                    else None
                ),
            }
        )
        return _obj
