version: '3.6'
services:
  service:
    build:
      context: .
      target: service
    ports:
      - "8080:8080"
    command: uvicorn unity_sps_ogc_processes_api.main:app --host 0.0.0.0 --port 8080
