name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker Image Tag"
        required: false
        default: "development-tag"

env:
  REGISTRY: ghcr.io
  TAG: ${{ github.event.inputs.tag }}
  UNITY-SPS-OGC-PROCESSES-API: ${{ github.repository }}/unity-sps-ogc-processes-api

jobs:
  build-unity-sps-ogc-processes-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for the Unity SPS OGC Processes API Docker image
        id: metascheduler
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.UNITY-SPS-OGC-PROCESSES-API }}
      - name: Build and push the Unity SPS OGC Processes API Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.UNITY-SPS-OGC-PROCESSES-API }}:${{ env.TAG }}
          labels: ${{ steps.metascheduler.outputs.labels }}
